In [2]:
import numpy as np

In [3]:
lst =[1,2,3,4,5]
arr =np.array(lst,dtype='float32')
print(arr)

[1. 2. 3. 4. 5.]


In [4]:
print(type(arr))

<type 'numpy.ndarray'>


A key difference between an array and a list is that arrays allow you to
perform vectorized operations while a list is not designed to handle vector
operations. A vector operation means a function gets applied to every item in
the array.
Say we have a list and we want to multiply each item by 2. We cannot do
element-wise operations by simply saying “mylist * 2”. However, we can do so
on a NumPy array.

In [69]:
# for example
lst*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [5]:
arr1 = np.array([1, 2, 3, 4])
print(arr1)

print(arr1*2)
print(arr1+2)
print(arr1*500)
print(arr1*arr1)

[1 2 3 4]
[2 4 6 8]
[3 4 5 6]
[ 500 1000 1500 2000]
[ 1  4  9 16]


Some other key differences between Python built-in lists and NumPy arrays
are:
Array size cannot be changed after creation, you will have to create a
new array or overwrite the existing one to change size.
Unlike lists, all items in the array must be of the same dtype.
An equivalent NumPy array occupies much less space than a Python list
of lists.


In [6]:
# Create an integer array of length 100 filled with zeros
np.zeros(100, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Create an integer array of length 100 filled with ones
np.ones(100, dtype=int)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
# Create a 3x3 floating-point array filled with 1s

np.ones((3,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 3
# (this is similar to the built-in range() function)

np.arange(0,20,3)


array([ 0,  3,  6,  9, 12, 15, 18])

In [10]:
# Create an array of hundred values evenly spaced between 0 and 1
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [11]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.55883468, 0.37638268, 0.58123853],
       [0.11873606, 0.91086856, 0.19859646],
       [0.04312355, 0.48153631, 0.57042317]])

In [12]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[9, 3, 4],
       [5, 0, 1],
       [1, 7, 1]])

In [13]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))


array([[-1.22942788,  0.1444988 , -0.15130875],
       [-0.89777171,  1.90275309,  1.48886566],
       [-0.23297461,  2.93481535,  0.11751347]])

In [14]:
np.random.randint(10, size=6) # One-dimensional array of random integers

array([2, 8, 7, 3, 3, 3])

In [15]:
np.random.randint(54, size=(3, 3)) # Two-dimensional array of random integers


array([[16, 20, 33],
       [41, 31, 45],
       [51, 49, 35]])

In [16]:
np.random.randint(10, size=(3, 3, 3)) # Three-dimensional array of random integers

array([[[6, 3, 0],
        [2, 6, 5],
        [6, 1, 9]],

       [[6, 6, 1],
        [6, 8, 5],
        [8, 1, 4]],

       [[9, 0, 7],
        [9, 8, 4],
        [8, 8, 5]]])

Each array has the following attributes:
ndim : the number of dimensions
shape : the size of each dimension
size : the total size of the array
dtype : the data type of the array
itemsize : the size (in bytes) of each array element
nbytes : the total size (in bytes) of the array


In [17]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)
print(arr1.itemsize)
print(arr1.nbytes)

1
(4L,)
4
int32
4
16


# Array Indexing and Slicing

In [18]:
# Input array
x = np.array([1, 3, 4, 4, 6, 4])

print(x[1])
print(x[-1])
print(x[3])

3
4
4


In [19]:
# In a multidimensional array, we need to specify row and column index. Given input array x2:
x2 = np.array([[3, 2, 5, 5],[0, 1, 5, 8], [3, 0, 5, 0]])
x2[1,0]

0

Array Slicing #

Slicing array is a way to access subarrays, i.e., accessing multiple or a range of
elements from an array instead of individual items. In other words, when you
slice arrays you get and set smaller subsets of items within larger arrays.
Again, we need to use square brackets to access individual elements. But this
time, we also need the slice notation, “:” to access a slice or a range of
elements of a given array, x:
x[start:stop:step]

In [20]:
x1 = np.arange(10) # Input array



In [21]:
x1[3:7:2]

array([3, 5])

In [22]:
# Get the first 5 elements of x
x1[:5]

array([0, 1, 2, 3, 4])

In [23]:
# Elements after index 4
x1[4:]

array([4, 5, 6, 7, 8, 9])

In [24]:
# From 4th to 6th position
x1[4:7]

array([4, 5, 6])

In [25]:
# Return elements at even place (every other element)
x1[::2]

array([0, 2, 4, 6, 8])

In [26]:
#return elements from 1st position step by 2 (every other element starting at index 1)
x1[1::2]

array([1, 3, 5, 7, 9])

In [27]:
#reverse the array
x1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
# reverse every other element starting from index 5
x1[5::-2]

array([5, 3, 1])

In [29]:
x2 = np.array([[0,1,2], [3,4,5], [6,7,8]])

x2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
# all rows, every other column

x2[:3,::2]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [31]:
x2[::-1, ] 

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [32]:
x2[::-1,::-1]

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

Note: Array slices are not copies of the arrays. This means that if we
want to do a modification on the array obtained from the slicing
operation without changing the original array, we have to use the copy()
method:

In [33]:
x2_subcopy = x2[::-1, ::-1].copy()
x2_subcopy

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [34]:
x2


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Reshaping and Concatenation

In [35]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
x = np.array([1, 2, 3])
print(x)
# row vector via reshape
x_rv= x.reshape((1, 3))
print(x_rv)
# column vector via reshape
x_cv = x.reshape((3, 1))
print(x_cv)


[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [37]:
# We can concatenate two or more arrays at once.
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [11,11,11]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 11, 11, 11])

In [38]:
# We can also concatenate 2-dimensional arrays.
grid = np.array([[1,2,3] , [4,5,6]])
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[9,10,11]])
np.vstack([x,grid]) # vertically stack the arrays


array([[ 3,  4,  5],
       [ 1,  2,  3],
       [ 9, 10, 11]])

In [40]:
z = np.array([[19],[19]])
np.hstack([grid,z]) # horizontally stack the arrays

array([[ 1,  2,  3, 19],
       [ 9, 10, 11, 19]])

In [41]:
x =np.arange(10)
np.split(x,[3,6,9])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([9])]

In [42]:
x =np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [44]:
np.vsplit(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# Computations on NumPy Arrays

In [45]:
theta = np.linspace(0, np.pi, 4)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))


('theta = ', array([0.        , 1.04719755, 2.0943951 , 3.14159265]))
('sin(theta) = ', array([0.00000000e+00, 8.66025404e-01, 8.66025404e-01, 1.22464680e-16]))
('cos(theta) = ', array([ 1. ,  0.5, -0.5, -1. ]))
('tan(theta) = ', array([ 0.00000000e+00,  1.73205081e+00, -1.73205081e+00, -1.22464680e-16]))


In [46]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

('x =', [1, 2, 3])
('e^x =', array([ 2.71828183,  7.3890561 , 20.08553692]))
('2^x =', array([2., 4., 8.]))
('3^x =', array([ 3,  9, 27]))
('ln(x) =', array([0.        , 0.69314718, 1.09861229]))
('log2(x) =', array([0.       , 1.       , 1.5849625]))
('log10(x) =', array([0.        , 0.30103   , 0.47712125]))


Calling the reduce method
Say we want to apply some operation to reduce an array to a single value.
We can use the reduce() method for this. This method repeatedly applies the
given operation to the elements of an array until only a single result remains.
For example, calling reduce on the add functions returns the sum of all
elements in the array:


In [47]:
x = np.arange(1, 6)
sum_all = np.add.reduce(x)
print(x)
print(sum_all)


[1 2 3 4 5]
15


Calling the accumulate method
If we need to store all the intermediate results of the computation, we can
use accumulate() instead:

In [48]:
x = np.arange(1, 6)
sum_acc = np.add.accumulate(x)
print(x)
print(sum_acc)


[1 2 3 4 5]
[ 1  3  6 10 15]


In [49]:
x = np.random.random(100)
# Sum of all the values
print("Sum of values is:", np.sum(x))
# Mean value
print("Mean value is: ", np.mean(x))
#For min, max, sum, and several other NumPy aggregates,
#a shorter syntax is to use methods of the array object itself,
# i.e. instead of np.sum(x), we can use x.sum()
print("Sum of values is:", x.sum())
print("Mean value is: ", x.mean())
print("Max value is: ", x.max())
print("Min value is: ", x.min())


('Sum of values is:', 50.154625541971875)
('Mean value is: ', 0.5015462554197188)
('Sum of values is:', 50.154625541971875)
('Mean value is: ', 0.5015462554197188)
('Max value is: ', 0.996532616401565)
('Min value is: ', 0.015614775148068194)


In [50]:

grid = np.random.random((3, 4))
print(grid)
print("Overall sum:", grid.sum())
print("Overall Min:", grid.min())
# Row wise and column wise min
print("Column wise minimum: ", np.amin(grid, axis=0))
print("Row wise minimum: ", np.amin(grid, axis=1))


[[0.99447047 0.02950755 0.13631438 0.67853037]
 [0.44930254 0.52655849 0.19095986 0.66267775]
 [0.72611886 0.10847274 0.70885841 0.18980051]]
('Overall sum:', 5.401571933869926)
('Overall Min:', 0.029507545422870707)
('Column wise minimum: ', array([0.44930254, 0.02950755, 0.13631438, 0.18980051]))
('Row wise minimum: ', array([0.02950755, 0.19095986, 0.10847274]))


# Comparisons and Boolean Masks #

In [51]:
x =np.arange(20)
print(x)
print(x>2)
print(x>=4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[False False False False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]


In [52]:
print(x)
# How many thavalues less n 6?
print(np.count_nonzero(x < 6))
# Are there any values greater than 8?
print(np.any(x > 8))
# Are all values less than 10?
print(np.all(x < 10))

print(np.count_nonzero(x<10))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
6
True
False
10


In [53]:
# Random integers between [0, 10) of shape 3x3
x = np.random.randint(0, 10, (3, 3))
print(x)
# Boolean array
print(x < 6)
# Boolean mask
print(x[x < 6])

[[6 8 2]
 [6 3 0]
 [5 6 5]]
[[False False  True]
 [False  True  True]
 [ True False  True]]
[2 3 0 5 5]


# Execrise

In [54]:
#Q1.Create a null vector (all zeros) of size 10 and set it in the variable called “Z”. #
z =np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
#Create a 1D array of numbers from 0 to 9 and set it in the variable called “arr”.
arr =np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
#Create a 3x3x3 array with random values and set it in the variable called “arr”
arr =np.random.random((3,3,3))
arr

array([[[0.52113356, 0.39552366, 0.97162096],
        [0.36941388, 0.6566143 , 0.77292008],
        [0.16583998, 0.33453775, 0.09249346]],

       [[0.33362428, 0.91861551, 0.2152808 ],
        [0.03673919, 0.46517816, 0.8671919 ],
        [0.13353335, 0.08780794, 0.78685746]],

       [[0.51405053, 0.35657918, 0.03391908],
        [0.61864981, 0.08234516, 0.92167995],
        [0.73923874, 0.29594529, 0.53462846]]])

In [57]:
#Create a 10x10 array with random values called “arr4”. Find its minimum and
#maximum values and set them in the variables called “min_val” and “max_val”
#respectively.
arr4 =np.random.randint(0,30,(10,10))
min_val =np.min(arr4)
max_val =np.max(arr4)
print(min_val,max_val)


(0, 29)


In [58]:
'''
First create a 1D array with numbers from 1 to 9 and then convert it into a 3x3
grid. Store the nal answer in the variable called “grid”. 

'''
grid =np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
#Replace the maximum value in the given vector, “arr6”, with -1
arr6 =np.arange(10)

max_ =np.max(arr6)
x =np.where(arr6==max_)


arr6[x]=-1
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, -1])

In [63]:
#Reverse the rows of the given 2D array, “arr7”. #
arr7 = np.arange(9).reshape(3,3)
print(arr7)
arr7[::,::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [66]:
'''
Subtract the mean of each row of the given 2D array, “arr8”, from the values in
the array. Set the updated array in “transformed_arr8”. #
To get the mean along the row axis, you can use the numpy.mean method,
mean(axis=1, keepdims=True) .

'''
arr8 = np.random.rand(3, 10)
print(arr8)

x =np.mean(arr8,axis=1, keepdims=True)
print(x)
print(arr8-x)

[[0.36180382 0.54681763 0.02849304 0.84093406 0.60571455 0.62995385
  0.72687222 0.87910995 0.46321059 0.2553517 ]
 [0.60484625 0.29943675 0.49601636 0.07807819 0.86080905 0.6961125
  0.66508351 0.81617217 0.69492877 0.1694852 ]
 [0.37703174 0.55609871 0.7367058  0.44920835 0.5563598  0.02021363
  0.91947571 0.49369093 0.92360609 0.81166071]]
[[0.53382614]
 [0.53809687]
 [0.58440515]]
[[-0.17202232  0.01299148 -0.5053331   0.30710792  0.07188841  0.09612771
   0.19304608  0.34528381 -0.07061555 -0.27847444]
 [ 0.06674937 -0.23866012 -0.04208052 -0.46001868  0.32271217  0.15801562
   0.12698663  0.2780753   0.1568319  -0.36861168]
 [-0.20737341 -0.02830644  0.15230065 -0.1351968  -0.02804535 -0.56419152
   0.33507057 -0.09071422  0.33920094  0.22725557]]
